# Generated by Django 4.0.6 on 2023-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('short_description', models.TextField(verbose_name='توضیح کوتاه')),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده')),
                ('avatar', models.ImageField(upload_to='images/blog_avatars', verbose_name='آوارتار بلاگ')),
                ('background_image', models.ImageField(upload_to='images/blog_backgrounds', verbose_name='تصویر بکگراند')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('text_content', models.TextField(verbose_name='متن مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'بلاگ',
            },
        ),
    ]
