# Generated by Django 4.0.6 on 2023-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('website', models.CharField(max_length=255, null=True, verbose_name='ویسایت')),
                ('message', models.TextField(max_length=255, verbose_name='متن پیام')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_read_by_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'لیست پیام های تماس با ما',
            },
        ),
    ]
