# Generated by Django 4.0.6 on 2023-04-30 08:07

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فصل')),
                ('number', models.IntegerField(verbose_name='شماره فصل')),
                ('description', models.TextField(default='', verbose_name='توضیحات فصل')),
                ('background_image', models.ImageField(upload_to='images/backgrounds', verbose_name='تصویر بکگراند')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'لیست فصل ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'لیست تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('main_episode', models.IntegerField(default=1)),
                ('season_episode', models.IntegerField(default=1, verbose_name='شماره قسمت فصل')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('producer', models.CharField(max_length=255, verbose_name='تهیه کننده')),
                ('short_description', models.TextField(default='', verbose_name='توضیحات کوتاه')),
                ('content', django_quill.fields.QuillField(null=True)),
                ('avatar', models.ImageField(upload_to='images/avatars', verbose_name='تصویر پادکست')),
                ('background_image', models.ImageField(upload_to='images/backgrounds', verbose_name='تصویر بکگراند')),
                ('podcast_file', models.FileField(upload_to='podcast_files', verbose_name='فایل پادکست')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast_module.season')),
                ('tags', models.ManyToManyField(related_name='tags', to='podcast_module.tag')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست ها',
            },
        ),
    ]
